---
- name: Installer et configurer docker
  hosts: all
  remote_user: vagrant
  become: true
  become_user: root

  tasks:
    - name: Remove packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: absent
      loop:
        - apache2
        - mysql-server
        - git
        - cowsay
        - nginx